services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: go_api
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - go_network
    volumes:
      - ./:/app

  db:
    image: postgres:15
    container_name: go_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - go_network

volumes:
  pgdata:

networks:
  go_network:
